version: '3'
services:
  db:
    container_name: database
    image: postgres
    env_file:
      - ./env/database.env
  web:
    container_name: webserver
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - ./env/database.env
      - ./env/web.env
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
